# For more info on HTTP files go to https://aka.ms/vs/httpfile

@hostname=localhost
@port=7266
@host={{hostname}}:{{port}}
@openaikey=""

# "/v1/models"

GET http://{{host}}/v1/models

###

# "/v1/chat/completions"

POST http://{{host}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{openaikey}}

{
    "model": "llama-2",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }

###

# "/v1/chat/completions"

POST http://{{host}}/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{openaikey}}

{
    "model": "llama-2",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "stream":true
}

###

# "/v1/completions"

POST http://{{host}}/v1/completions
Content-Type: application/json
Authorization: Bearer {{openaikey}}

{
}

###

# "/v1/embeddings"

POST http://{{host}}/v1/embeddings
Content-Type: application/json
Authorization: Bearer {{openaikey}}

{
}

###

# "/v1/engines/{modelName}/embeddings"

POST http://{{host}}/v1/gpt4/embeddings
Content-Type: application/json
Authorization: Bearer {{openaikey}}

{
}